try
Signed-off-by: GopherJ <alex_cj96@foxmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,44 +27,49 @@ jobs:
         with:
           key: cache-v1
       - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
-      - name: (linux) install vulkan sdk
-        shell: bash
+      - name: Run multiline
         run: |
-          set -e
+          brew install --cask firefox
+          brew install geckodriver
 
-          sudo apt-get update -y -qq
+      # - name: (linux) install vulkan sdk
+      #   shell: bash
+      #   run: |
+      #     set -e
 
-          # vulkan sdk
-          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
-          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.268-jammy.list https://packages.lunarg.com/vulkan/1.3.268/lunarg-vulkan-1.3.268-jammy.list
+      #     sudo apt-get update -y -qq
 
-          sudo apt-get update
-          sudo apt install -y vulkan-sdk
-      - name: (linux) install mesa
-        shell: bash
-        run: |
-          set -e
+      #     # vulkan sdk
+      #     wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
+      #     sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.268-jammy.list https://packages.lunarg.com/vulkan/1.3.268/lunarg-vulkan-1.3.268-jammy.list
 
-          curl -L --retry 5 https://github.com/gfx-rs/ci-build/releases/download/build18/mesa-23.3.1-linux-x86_64.tar.xz -o mesa.tar.xz
-          mkdir mesa
-          tar xpf mesa.tar.xz -C mesa
+      #     sudo apt-get update
+      #     sudo apt install -y vulkan-sdk
+      # - name: (linux) install mesa
+      #   shell: bash
+      #   run: |
+      #     set -e
 
-          # The ICD provided by the mesa build is hardcoded to the build environment.
-          #
-          # We write out our own ICD file to point to the mesa vulkan
-          cat <<- EOF > icd.json
-          {
-            "ICD": {
-                "api_version": "1.1.255",
-                "library_path": "$PWD/mesa/lib/x86_64-linux-gnu/libvulkan_lvp.so"
-            },
-            "file_format_version": "1.0.0"
-          }
-          EOF
+      #     curl -L --retry 5 https://github.com/gfx-rs/ci-build/releases/download/build18/mesa-23.3.1-linux-x86_64.tar.xz -o mesa.tar.xz
+      #     mkdir mesa
+      #     tar xpf mesa.tar.xz -C mesa
 
-          echo "VK_DRIVER_FILES=$PWD/icd.json" >> "$GITHUB_ENV"
-          echo "LD_LIBRARY_PATH=$PWD/mesa/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
-          echo "LIBGL_DRIVERS_PATH=$PWD/mesa/lib/x86_64-linux-gnu/dri" >> "$GITHUB_ENV"
+      #     # The ICD provided by the mesa build is hardcoded to the build environment.
+      #     #
+      #     # We write out our own ICD file to point to the mesa vulkan
+      #     cat <<- EOF > icd.json
+      #     {
+      #       "ICD": {
+      #           "api_version": "1.1.255",
+      #           "library_path": "$PWD/mesa/lib/x86_64-linux-gnu/libvulkan_lvp.so"
+      #       },
+      #       "file_format_version": "1.0.0"
+      #     }
+      #     EOF
+
+      #     echo "VK_DRIVER_FILES=$PWD/icd.json" >> "$GITHUB_ENV"
+      #     echo "LD_LIBRARY_PATH=$PWD/mesa/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
+      #     echo "LIBGL_DRIVERS_PATH=$PWD/mesa/lib/x86_64-linux-gnu/dri" >> "$GITHUB_ENV"
 
       - name: Run wasm tests
         run: |
@@ -80,6 +85,7 @@ jobs:
             "goog:chromeOptions": { "args": [ "disable-timeouts-for-profiling" ] }
           }
           EOF
+          WASM_BINDGEN_TEST_TIMEOUT=3600 wasm-pack test --release --headless --firefox --features no_std
           WASM_BINDGEN_TEST_TIMEOUT=3600 wasm-pack test --release --headless --chrome --features no_std
       - name: Run webgpu tests
         run: |
